### ISSUE TITLE
igb driver not recognized by XDP

### ISSUE THREAD

**Issue by sleek-geek** [gamemann/XDP-Firewall#11]
I have managed to run XDP in generic mode, however, it should run in native mode since [igb driver should be supported](https://github.com/iovisor/bcc/blob/master/docs/kernel-versions.md#xdp).

Driver:

_lspci_

```
01:00.0 Ethernet controller: Intel Corporation 82580 Gigabit Network Connection (rev 01)
01:00.1 Ethernet controller: Intel Corporation 82580 Gigabit Network Connection (rev 01)

```

_find /sys | grep drivers.*01:00_

```
/sys/bus/platform/drivers/ipmi_si/IPI0001:00
/sys/bus/pci/drivers/igb/0000:01:00.0
/sys/bus/pci/drivers/igb/0000:01:00.1

```

After _service xdpfw restart_

```
Nov 23 15:17:31 hp1007 systemd[1]: Started XDP Firewall tool..
Nov 23 15:17:33 hp1007 xdpfw[7774]: libbpf: Kernel error message: underlying driver does not support XDP in native mode
Nov 23 15:17:33 hp1007 xdpfw[7774]: Could not attach with DRV/native mode (Operation not supported)(-95).
Nov 23 15:17:34 hp1007 xdpfw[7774]: Loaded XDP program in SKB/generic mode.

```

**Comment by gamemann** [comment]
Hey @sleek-geek, can you confirm you are running kernel `5.10` or higher? You can find the kernel version by running `uname -r`.

Thank you!

**Comment by sleek-geek** [comment]
Hey @gamemann Forgot to add it.

_uname -r_

`5.4.0-72-generic`

**Comment by gamemann** [comment]
Hey @sleek-geek, no worries!

IGB XDP DRV support was added in kernel `5.10` or above.

You can use the following methods to install 5.10 or higher!

1. Install 5.10 or higher using the OS's package system such as `apt` or `yum` (sometimes you need to find backports).
2. Build the kernel from source.
3. For Ubuntu, install the latest mainline kernel using the following commands as root (this is what I usually do, but keep in mind these are the latest mainline kernels which could introduce bugs).

```
apt install wget
wget https://raw.githubusercontent.com/pimlie/ubuntu-mainline-kernel.sh/master/ubuntu-mainline-kernel.sh
chmod +x ubuntu-mainline-kernel.sh
sudo mv ubuntu-mainline-kernel.sh /usr/local/bin/
```

I hope the above helps and thank you!

**Comment by gamemann** [comment]
Hey @sleek-geek, I'm going to close this issue for now since your issue is related to the kernel version.

If you need any more help, please let me know!
