### ISSUE TITLE
usage

### ISSUE THREAD

**Issue by Tf-arch** [gamemann/XDP-Firewall#13]
I am trying to use this firewall but i could not understand completely, first I install
![image](https://user-images.githubusercontent.com/83109300/152567047-82f7b921-1a7b-447a-a733-b06cecdbc504.png)
I open config file /etc/xdpfw/xdpfw.conf
and change it to 
interface = "eno1";
updatetime = 0;

filters = (
    {
        enabled = true,
        action = 0,
        srcip = "103.22.221.170"
        dstip = "103.22.221.170"
    }
);

then I was assuming that the packets coming from 103.22.221.170 should be blocked.

then I capture packets from tcpdump from eno1

![image](https://user-images.githubusercontent.com/83109300/152567734-7fbf0fc4-5bbd-49a9-a63d-32e3ae62e22e.png)

but still i am seeing packets from 103.22.221.170.  

but i wanna block that IP 103.22.221.170 packets....

I am missing something or could not understand this?

**Comment by gamemann** [comment]
Hey and are you trying to block traffic coming **from** `103.22.221.170`? If so, remove the `dstip = "103.22.221.170"` line since you won't see any packets coming from `103.22.221.170` while going to `103.22.221.170`.

I hope the above helps!

**Comment by Tf-arch** [comment]
Thank you for your response..
Ibut still I am not successful in blocking traffic . I want to block traffic from 103.22.221.170 but my filter config file is not acting
![image](https://user-images.githubusercontent.com/83109300/152649077-6f7c05e8-43b9-4388-9b5a-90b9e5013fcf.png)
interface = "eno1";
updatetime = 15;

filters = (
    {
        enabled = true,
        action = 0,
        srcip="103.22.221.170",
        blocktime=1000
    }
)
still I am seeing packets from 103.22.221.170.
How could I know or check that xdp-program is loaded on interface eno1??

secondly I could install the xdp-firewall ONLY in root, other wise it was giving permission issues

![image](https://user-images.githubusercontent.com/83109300/152649119-dd05a76f-391b-4945-b1e9-840d21cf49eb.png)

but in root i can install 
![image](https://user-images.githubusercontent.com/83109300/152649155-9bafd46e-feab-4855-903c-ebf083c10b5e.png)

**Comment by gamemann** [comment]
Hey, I apologize for the delay. A lot has been going on recently in my life.

That config looks good and yes, you need perform `make install` as root.

You can type `ip a` and look at the `eno1` interface to confirm it has an XDP program loaded.

With that said, are you running `xdpfw` which starts the program? If so, does it start up okay and show packet statistics?

**Comment by Tf-arch** [comment]
Thanks for your responses. Hope everything goes well in your life.

xdpfw
![image](https://user-images.githubusercontent.com/83109300/153342455-b8f294da-871b-431a-a511-d49b3a81a8b8.png)
now its working and when i capture I cannot see any packet whose srcip 103.22.221.170
![image](https://user-images.githubusercontent.com/83109300/153342681-367fd2ca-5b88-43d0-989a-57d9e98624d3.png)


what will be filter rule if I want to drop those packets as well whose destination IP is 103.22.221.170.  This means no packet should come and also go towards 103.22.221.170 from my device.

Secondly how to stop service or unload the program??

**Comment by gamemann** [comment]
Hey!

Unfortunately, the XDP program only supports inbound/ingress packets so unless if you're running this on a router that routes inbound/outbound packets for the specified machine, you won't be able to block any packets going out from the machine (egress). I'd assume this is running on the machine where the packets are originating from. The most you'll be able to do is block inbound packets since the XDP Firewall doesn't attach to the egress hook. If you want to block egress packets, you'll need to do it at the router level more than likely.

As for stopping the program, sending a keyboard interrupt via the CTRL + C keys is your best bet.

I hope the above helps!
