### ISSUE TITLE
filter doesnt work

### ISSUE THREAD

**Issue by JohansonIceBerg** [gamemann/XDP-Firewall#14]
HEY!

sorry to bother you but the PPS filtering doesnt work or does not work properly. The strictest but most effective PPS limit which is 2500 does not filter anything, but in fact lets more traffic through then even block. with my following configuration:

interface = "eno1";
updatetime = 15;
filters = (
   
    {
        enabled = true,
        action = 0,
        pps = 2500,
        bps = 500,
        blocktime = 1000
    }
);

it does not even block anything.

Can you please help me understand why its not doing what its meant to do if its meant to help filter.

thank you.

-Johanson

**Comment by gamemann** [comment]
Hey, I apologize for the really late reply! A lot has been going on in my life recently.

Can you confirm the XDP program is loaded via the `ip a` or `ip link` commands?

Thank you!

**Comment by JohansonIceBerg** [comment]
Yes it is loaded

**Comment by gamemann** [comment]
When testing the rate-limiting, do you use the same source IP/port or different combinations?
