### ISSUE TITLE
Daemon mode doesn't unload xdp when service stopped

### ISSUE THREAD

**Issue by omicronn88** [gamemann/XDP-Firewall#15]
Hi, really nice work you did. I find this tool very useful.
However, I noticed that when I start it via systemd service the xdp program doesn't get unloaded from an interface after I stopped it, hence the firewall continues working.
I fixed it by adding this line in the systemd unit but I don't know if it's the best solution
`ExecStopPost=/bin/bash -c "/bin/ip link set dev $(grep -E ^interface /etc/xdpfw/xdpfw.conf | sed -En 's/^.+=|[\"; ]//gp') xdp off"`

**Comment by gamemann** [comment]
Hey and thank you!

Would you be able to make a pull request for this? I don't want to make a commit for it because I'd prefer if you got the credit for that :)

**Comment by omicronn88** [comment]
Sure, done :)
