### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by natesales** [gamemann/XDP-Firewall#19]
This is great work! Can you add a license to cover this repo?

ref: https://choosealicense.com/no-permission/

**Comment by gamemann** [comment]
Hey and thank you :) I will look into this soon!

**Comment by natesales** [comment]
Just following up on this, is there a license you would feel comfortable with adding? GPL/MIT/etc?

**Comment by gamemann** [comment]
Hey, I finally got around to doing this and went with a MIT license. I am sorry for the long delay, been really busy with life the past few months.
