### ISSUE TITLE
Add Feature detect Hex and String?

### ISSUE THREAD

**Issue by namecloudz** [gamemann/XDP-Firewall#37]
i want you add feature detect hex and string to protection.

**Comment by gamemann** [comment]
Hey, I'm sorry for the delay on this!

Initially, this firewall included payload matching via hex and string. However, I ran into a lot of XDP/BPF limitations and ended up removing support in this firewall. Unfortunately, I haven't found a full solution yet. I did make [this](https://github.com/gamemann/XDP-Dynamic-Payload-Matching) repository which includes working XDP code to perform dynamic payload matching, but it doesn't include an option to match payload at a certain offset in the payload which doesn't allow us to perform partial matching.
