### ISSUE TITLE
LibBPF fails to load xdp_prog

### ISSUE THREAD

**Issue by g00g1** [gamemann/XDP-Firewall#39]
I am sorry to bother you once more again, but since my previous issue (#38) I have tried to change environment where I am trying to evaluate and hack on this project.

The new host is:
CPU: 2x Intel(R) Xeon(R) Silver 4208
NIC: Intel Corporation Ethernet Controller XL710 for 40GbE QSFP+ (i40e)
Kernel: 5.14.0-70.13.1.el9_0.x86_64

I have successfully built xdpfw, but when running `xdpfw -t 5` I have encountered LibBPF error, full log is attached below

[xdpfw.txt](https://github.com/gamemann/XDP-Firewall/files/11477115/xdpfw.txt)

UPD: exactly the same behavior was reproduced on another machine (as in issue #38)

**Comment by gamemann** [comment]
Hey, thank you for reporting this and no need to be sorry!

It appears in newer Linux kernels the BPF limitations are more strict. Although, the complexity limit has always been 1 million which makes this issue strange to me. The firewall has worked for years until this issue arose.

I've decreased the maximum filters from *100* to *90* in commit [8fbab9b](https://github.com/gamemann/XDP-Firewall/commit/8fbab9bf823359ee73ccc3c5f89fcd4df61ae15a) which resolves the issue without needing to apply a patch to the kernel. I'll update the README soon and add information from my XDP Forwarding project [here](https://github.com/gamemann/XDP-Forwarding/tree/master/patches) that goes over how to increase the limits along with including a patch if anybody needs more than 90 filtering rules.

**Comment by gamemann** [comment]
I'm going to close this for now since the firewall builds successfully. Thank you again for the report!
